service: yubiori

custom:
  defaultStage: dev
  api_version: v0

provider:
  name: aws
  runtime: java11
  region: ap-northeast-1
  stage: ${opt:stage, self:custom.defaultStage}
  environment:
    ${file(./env.yml)}

package:
  artifact: target/scala-2.13/handler.jar

functions:
  notify:
    handler: handler.Notify

  api:
    handler: handler.Get
    events:
      - http:
          path: yubiori/v1/get
          method: get