name: scala-sls

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:

    - name: checkout
      uses: actions/checkout@v1

    - name: build
      id: sbt
      uses: lokkju/github-action-sbt@11-1.3.0-2.13.0
      with:
        commands: assembly
        sbt_project_directory: ./

    - name: configure aws
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: get env
      run: |
        aws s3 cp s3://limit7412-workflow-env/yubiori/dev/env.yml .

    - name: setup node.js
      uses: actions/setup-node@v1

    - name: install sls
      run: npm i -g serverless

    - name: deploy
      run: sls deploy -s dev > ./result.txt

    - name: push result
      run: |
        aws s3 cp ./result.txt s3://limit7412-workflow-env/yubiori/result/result-dev.txt